export const BORDER_LIGHT_COLOR = '#EAEAF1';
export const BORDER_DARK_COLOR = '#EAEAF1';

export const MENU_TITLE_COLOR = '#626264';
export const MENU_TEXT_LIGHT_COLOR = 'black';
export const MENU_TEXT_DARK_COLOR = '#E7E7E8';

export const MENU_TEXT_DESTRUCTIVE_COLOR_LIGHT = '#D81C1D';
export const MENU_TEXT_DESTRUCTIVE_COLOR_DARK = '#D81C1D';

export const MENU_BACKGROUND_COLOR_LIGHT = 'white';
export const MENU_BACKGROUND_COLOR_DARK = '#222329';